composer.json
example/ServerEmulator.php
example/Workflow/PizzaDelivery.php
example/client.php
src/Declaration/Workflow.php
src/Declaration/WorkflowInterface.php
src/Meta/Native/NativeReader.php
src/MutableWorkerInterface.php
src/Protocol/ClientInterface.php
src/Protocol/Json.php
src/Protocol/JsonRpcProtocol.php
src/Protocol/Message/ErrorResponse.php
src/Protocol/Message/Message.php
src/Protocol/Message/Request.php
src/Protocol/Request/CompleteWorkflow.php
src/Protocol/Request/CreateWorker.php
src/Protocol/Request/ExecuteActivity.php
src/Protocol/Request/StartWorker.php
src/RestartableExecutor.php
src/Runtime/ActivityOptions.php
src/Runtime/Queue/EntryInterface.php
src/Runtime/Request/CompleteWorkflow.php
src/Runtime/Request/ExecuteActivity.php
src/Runtime/Route/StartWorkflow.php
src/Runtime/Workflow/Executor.php
src/Runtime/WorkflowContext.php
src/Runtime/WorkflowContextInterface.php
src/Worker.php

Added features:
- Basic options for Activity execution
- Query and Signal handlers support
- Basic PSR-3 implementation
- Separated workflow executor
- Complete generation of attribute-based declarations
Fixed bugs:
- Incorrect answer when resolving a promise
- Memory leaks when resolving deferreds
Well and something else...

Comprehensive improvements

---

src/Internal/Transport/Request/CompleteWorkflow.php
src/Internal/Transport/Request/SignalExternalWorkflow.php
src/Internal/Workflow/ChildWorkflowStub.php
src/Internal/Workflow/Process/Process.php
src/Workflow/ChildWorkflowOptions.php
src/Workflow/WorkflowContext.php

- removed default child workflow ID
- bugfix: invalid signal parameters for child workflow stub
- better exception passing on failed workflows

Integration bug fixes

---

src/Internal/Marshaller/Type/DateTimeType.php
src/Internal/Support/DateTime.php
src/Worker/Environment/Environment.php

Add RFC3339 with nanoseconds support

---

src/Activity/ActivityInterface.php
src/Activity/ActivityMethod.php
src/DataConverter/DataConverter.php
src/DataConverter/Type.php
src/Internal/Declaration/Prototype/WorkflowPrototype.php
src/Internal/Declaration/Reader/WorkflowReader.php
src/Internal/Workflow/ActivityStub.php
src/Internal/Workflow/ChildWorkflowProxy.php
src/Internal/Workflow/ChildWorkflowStub.php
src/Workflow/ActivityStubInterface.php
src/Workflow/ChildWorkflowStubInterface.php
src/Workflow/QueryMethod.php
src/Workflow/ReturnType.php
src/Workflow/SignalMethod.php
src/Workflow/WorkflowInterface.php
src/Workflow/WorkflowMethod.php

Adds return type feature:
```php
#[ReturnType(name: ReturnType::TYPE_INT)]
public function handle(): iterable
{
yield Workflow::newTimer(42);
return 42;
}
```

Add optional return type attribute

---

resources/.phpstorm.meta.php
src/Internal/Client/WorkflowProxy.php
src/Internal/Declaration/ActivityInstance.php
src/Internal/Declaration/Prototype/Prototype.php
src/Internal/Declaration/Prototype/PrototypeInterface.php
src/Internal/Declaration/Reader/WorkflowReader.php
src/Internal/Declaration/WorkflowInstance.php

1) Remove the ability to register anonyumous functions as activities/workflows
2) Use method context workflow name as default instead of root class name
3) Added IDE helper for  Workflow::newContinueAsNewStub
4) A little codestyle typo

Common improvements

---

src/Internal/ServiceContainer.php
src/Internal/Transport/Router/GetWorkerInfo.php
src/Worker/Worker.php
src/Worker/WorkerInterface.php
src/Worker/WorkerOptions.php
src/WorkerFactory.php

Add worker options support

---

src/Activity.php
src/Activity/ActivityContext.php
src/Activity/ActivityContextInterface.php
src/DataConverter/EncodedValues.php
src/Internal/Marshaller/TypeFactory.php
src/Internal/ServiceContainer.php
src/Internal/Transport/Router/GetWorkerInfo.php
src/Internal/Transport/Router/InvokeActivity.php
src/Internal/Workflow/Process/Scope.php
src/Workflow.php
src/Workflow/ScopedContextInterface.php
src/Workflow/WorkflowContext.php
src/Workflow/WorkflowContextInterface.php

Replace magic proxy calls of Activity::xxx to real methods that refers to activity context.

Activities facade improvements

---

src/Internal/Transport/Router/StackTrace.php

Removing unnecessary debug stmt

Remove error_log debug statement

---

composer.json

Use only RR worker instead of full RR stack

Improve composer dependencies

---

.github/workflows/testing.yml

- Added `stability` flag in CI
- Added `--no-interaction` flag in CI

Fix functional tests in CI

---

src/Client/WorkflowClient.php

Fixes https://github.com/temporalio/sdk-php/issues/98

Annotations fix in workflow client

---

src/Client/WorkflowClient.php
src/Promise.php

Improve psalm types

---

src/Common/RetryOptions.php

Fixed https://github.com/temporalio/sdk-php/issues/105

Fix RetryOptions Maximum Interval

---

README.md
composer.json
src/Activity/ActivityOptions.php

Links to docs have been updated.
Doc's pages URLs have changed.
1. Closes issue: 
N/A
N/A
N/A

Updating links to docs

---

src/Workflow.php
src/Workflow/WorkflowContextInterface.php

Fixed incorrect psalm annotations that caused this:
The code itself is correct.

Fix DateInterval annotations

---

src/Internal/Workflow/ScopeContext.php
src/Internal/Workflow/WorkflowContext.php
tests/Unit/WorkflowContext/AwaitWithTimeoutTestCase.php

Resolve related awaits once one of the group resolves
Resolves #122

Fix awaits

---

.github/workflows/testing.yml
src/Internal/Declaration/Prototype/ActivityCollection.php
src/Internal/Transport/Router/InvokeActivity.php
src/Worker/Worker.php
src/Worker/WorkerInterface.php
tests/Unit/Framework/WorkerMock.php
tests/Unit/Router/DummyActivity.php
tests/Unit/Router/InvokeActivityTestCase.php

Added activity finalizer - a callback being called after each activity. This can be used to clean up resources in your application.

Introduce activity finalizer

---

src/Worker/WorkerInterface.php

Fix PHPDoc for registerActivity

---

src/Activity/ActivityInterface.php
src/Activity/ActivityOptionsInterface.php
src/Activity/LocalActivityInterface.php
src/Activity/LocalActivityOptions.php
src/Internal/Declaration/Prototype/ActivityPrototype.php
src/Internal/Declaration/Reader/ActivityReader.php
src/Internal/Transport/Request/ExecuteLocalActivity.php
src/Internal/Transport/Router/InvokeActivity.php
src/Internal/Transport/Router/InvokeLocalActivity.php
src/Internal/Workflow/ActivityProxy.php
src/Internal/Workflow/ActivityStub.php
src/Internal/Workflow/WorkflowContext.php
src/Worker/Worker.php
src/Workflow.php
src/Workflow/ActivityStubInterface.php
src/Workflow/WorkflowContextInterface.php
tests/Fixtures/src/Workflow/ActivityStubWorkflow.php
tests/Unit/Activity/ActivityPrototypeTestCase.php
tests/Unit/Activity/DummyLocalActivity.php
tests/Unit/Declaration/Fixture/FixedReader.php

Should be merged only once it is supported on RR side.

Local activity [WIP]

---

src/Internal/Workflow/WorkflowContext.php
tests/Unit/Framework/Server/CommandHandler/CommandHandlerFactory.php
tests/Unit/Framework/Server/CommandHandler/GetVersionHandler.php
tests/Unit/WorkflowContext/GetVersionTestCase.php

Fix workflow get version

---

tests/Unit/Protocol/EncodingTestCase.php

Test for the previous PR - https://github.com/temporalio/sdk-php/pull/181

Add test for null values decoding

---

src/Internal/Transport/Router/StartWorkflow.php
tests/Unit/Router/DummyWorkflow.php
tests/Unit/Router/StartWorkflowTestCase.php

Don't fail on StartWorkflow

---

src/Client/GRPC/Context.php

Send SDK client name/version to Temporal

---

src/Internal/Workflow/ScopeContext.php
src/Internal/Workflow/WorkflowContext.php
tests/Fixtures/src/Workflow/AsyncClosureWorkflow.php
tests/Functional/Client/AsyncClosureTestCase.php

Fix async closure cancellation

---

.github/workflows/testing.yml
composer.json

Support Symfony 4,5,6.
Resolves #195

Add support for multiple symfony versions

---

src/Internal/Declaration/Prototype/ActivityCollection.php

Fix typo in the name and initialization.

Fix activity finalizer

---

src/Internal/Workflow/ChildWorkflowStub.php
src/Workflow/ChildWorkflowStubInterface.php
testing/src/Environment.php
tests/Fixtures/src/Workflow/AbandonedChildWithTimerWorkflow.php
tests/Fixtures/src/Workflow/ParentWithAbandonedChildWorkflow.php
tests/Functional/Client/AbandonedChildWorkflowTestCase.php
tests/docker-compose.yaml

Fix: abandoned child workflow start

---

src/Client/GRPC/BaseClient.php

Extend base client for ssl

---

src/Internal/Transport/Request/UpsertSearchAttributes.php
src/Internal/Workflow/ScopeContext.php
src/Internal/Workflow/WorkflowContext.php
src/Workflow.php
src/Workflow/WorkflowContextInterface.php
tests/Fixtures/src/Workflow/UpsertSearchAttributesWorkflow.php
tests/Functional/Client/UpsertSearchAttributesWorkflowTestCase.php
tests/SearchAttributeTestInvoker.php
tests/bootstrap.php

https://github.com/temporalio/sdk-php/issues/76
Same functionality like in GO-SDK - https://github.com/temporalio/samples-go/tree/main/searchattributes
Dependecy: https://github.com/temporalio/roadrunner-temporal/pull/275
1. Closes
https://github.com/temporalio/sdk-php/issues/76
Integration tests

feat: upsert search attributes

---

src/Internal/Declaration/Instance.php
src/Internal/Declaration/InstanceInterface.php
src/Internal/Declaration/Prototype/WorkflowPrototype.php
src/Internal/Declaration/WorkflowInstance.php
src/Internal/Declaration/WorkflowInstance/SignalQueue.php
src/Internal/Declaration/WorkflowInstanceInterface.php
src/Worker/Worker.php
src/Workflow/ChildWorkflowStubInterface.php

Updated type annotations; Fixed few psalm issues.
We should move to better static analyze coverage. Existing attributes should be more correct.
To test it: run `vendor/bin/psalm` wtih `errorLevel="6"` before and after the PR

[Maintenance] Fix psalm issues

---

.github/workflows/run-test-suite.yml
testing/src/Environment.php

Environment variable `GITHUB_TOKEN` now accessible inside the workflow run
Was discussed in the Discord
1. Closes 

fix(ci): GitHub API 403 error fixed

---

src/Interceptor/ActivityInboundInterceptor.php
src/Interceptor/Trait/ActivityInboundInterceptorTrait.php
src/Interceptor/Trait/WorkflowClientCallsInterceptorTrait.php
src/Interceptor/Trait/WorkflowInboundInterceptorTrait.php
src/Interceptor/Trait/WorkflowOutboundRequestInterceptorTrait.php
src/Interceptor/WorkflowClientCallsInterceptor.php
src/Interceptor/WorkflowInboundInterceptor.php
src/Interceptor/WorkflowOutboundCalls/CancelExternalWorkflowInput.php
src/Interceptor/WorkflowOutboundCalls/ExecuteActivityInput.php
src/Interceptor/WorkflowOutboundCalls/ExecuteChildWorkflowInput.php
src/Interceptor/WorkflowOutboundCalls/ExecuteLocalActivityInput.php
src/Interceptor/WorkflowOutboundCalls/SideEffectInput.php
src/Interceptor/WorkflowOutboundCalls/SignalExternalWorkflowInput.php
src/Interceptor/WorkflowOutboundCalls/TimerInput.php
src/Interceptor/WorkflowOutboundCallsInterceptor.php
src/Interceptor/WorkflowOutboundRequestInterceptor.php
src/Internal/Transport/Request/CancelExternalWorkflow.php
src/Internal/Transport/Router/InvokeActivity.php
src/Internal/Workflow/ActivityProxy.php
src/Internal/Workflow/ExternalWorkflowStub.php
src/Internal/Workflow/WorkflowContext.php
src/Workflow/ExternalWorkflowStubInterface.php

> **Note**:
> The target branch is `interceptors`, not `master`.
- Set Activity context when ActivityInboundInterceptors pipeline is called
- Add `WorkflowOutboundCallsInterceptor` (WIP)
Part of #225
The PR introduces some fixes that are required to continue working on OpenTracing interceptors.

Update interceptor: add WorkflowOutboundCallsInterceptor

---

src/Client/GRPC/BaseClient.php
src/Client/WorkflowClient.php
src/Interceptor/GrpcClientInterceptor.php
src/Interceptor/WorkflowOutboundCalls/AwaitInput.php
src/Interceptor/WorkflowOutboundCalls/AwaitWithTimeoutInput.php
src/Interceptor/WorkflowOutboundCalls/CompleteInput.php
src/Interceptor/WorkflowOutboundCalls/ContinueAsNewInput.php
src/Interceptor/WorkflowOutboundCalls/GetVersionInput.php
src/Interceptor/WorkflowOutboundCalls/PanicInput.php
src/Interceptor/WorkflowOutboundCalls/UpsertSearchAttributesInput.php
src/Interceptor/WorkflowOutboundCallsInterceptor.php
src/Internal/Interceptor/Pipeline.php
src/Internal/Workflow/WorkflowContext.php
tests/Functional/Interceptor/GrpcClientInterceptor.php

> **Note**:
> The target branch is `interceptors`, not `master`.
- Add `GrpcClientInterceptor`
- Add more methods for `WorkflowOutboundCallsInterceptor` (WIP)
Part of #225
The PR introduces new interceptor to make `SystemInfoInterceptor`.

Update WorkflowOutboundCallsInterceptor , add GrpcClientInterceptor

---

src/Internal/Marshaller/Type/ObjectType.php
tests/Unit/DTO/Type/ObjectType/ObjectTypeTestCase.php
tests/Unit/DTO/Type/ObjectType/Stub/NullableProperty.php

Fixed nullable object type detection on an object unmarshalling
How was this tested: added autotests
Any docs updates needed? No

Fix marshalling/unmarshalling of nullable object type

---

psalm-baseline.xml
src/Client/CountWorkflowExecutions.php
src/Client/Paginator.php
src/Client/WorkflowClient.php
src/Client/WorkflowClientInterface.php

Added `WorkflowClient::countWorkflowExecutions()` method
1. Closes #291
2. How was this tested: manually
3. Any docs updates needed? I think the block [Observability / Visibility](https://docs.temporal.io/dev-guide/php/observability#visibility) may be updated

Add API to count workflows

---

src/DataConverter/ProtoJsonConverter.php
tests/Functional/DataConverterTestCase.php

Replaced `serializeToString` with `serializeToJsonString` in `ProtoJsonConverter`
- added test

Fix: ProtoJsonConverter must convert data in json

---

psalm-baseline.xml
src/Common/RetryOptions.php
src/Internal/Mapper/ScheduleMapper.php
tests/Unit/Schedule/Mapper/WorkflowExecutionInfoMapperTest.php

Fixed RetryPolicy message marshalling
1. Closes #380 

Fix Schedule RetryPolicy marshalling 

---

psalm-baseline.xml
src/DataConverter/JsonConverter.php
src/Internal/Repository/RepositoryInterface.php
tests/Unit/DataConverter/JsonConverterTestCase.php

JsonConverter
Issue #385
1. Closes 

[JsonConverter] Fixed hydrate null value 

---

psalm-baseline.xml

Pslam baseline
Failed ci https://github.com/temporalio/sdk-php/actions/runs/7533225952/job/20505341696
1. Closes 

[Psalm] Update baseline

---

src/Client/GRPC/BaseClient.php
tests/Unit/Client/GRPC/BaseClientTestCase.php

Fixed condition that detects the timeout deadline is reached
Closes #431

Fix wrong "deadline is reached" detection

---

psalm-baseline.xml
src/Activity/ActivityCancellationType.php
src/Activity/ActivityOptions.php
src/Client/WorkflowOptions.php
src/Common/IdReusePolicy.php
src/Internal/Interceptor/Pipeline.php
src/Internal/Marshaller/Type/ActivityCancellationType.php
src/Internal/Marshaller/Type/ChildWorkflowCancellationType.php
src/Worker/ChildWorkflowCancellationType.php
src/Workflow.php
src/Workflow/ChildWorkflowCancellationType.php
src/Workflow/ChildWorkflowOptions.php
src/Workflow/ParentClosePolicy.php
tests/Unit/DTO/ActivityOptionsTestCase.php
tests/Unit/DTO/ChildWorkflowOptionsTestCase.php

Converted to Enum:
- ParentClosePolicy
- ChildWorkflowCancellationType
- ActivityCancellationType
1. Closes #437

Convert Policy Constants to Enums

---

psalm-baseline.xml
src/Internal/Declaration/Dispatcher/AutowiredPayloads.php
src/Internal/Declaration/Dispatcher/Dispatcher.php
src/Internal/Declaration/Dispatcher/DispatcherInterface.php
src/Internal/Declaration/Instance.php
src/Internal/Declaration/InstanceInterface.php
src/Internal/Declaration/Instantiator/Instantiator.php
src/Internal/Declaration/Instantiator/WorkflowInstantiator.php
src/Internal/Declaration/WorkflowInstance.php
src/Internal/Declaration/WorkflowInstance/SignalQueue.php
src/Internal/Declaration/WorkflowInstanceInterface.php
src/Internal/Marshaller/Type/ArrayType.php
src/Internal/Transport/Router/InvokeQuery.php
src/Internal/Transport/Router/InvokeUpdate.php
src/Internal/Workflow/Process/Process.php
src/Internal/Workflow/Process/Scope.php
src/Internal/Workflow/ProcessCollection.php
tests/Fixtures/src/Workflow/YieldScalarsWorkflow.php
tests/Functional/SimpleWorkflowTestCase.php
tests/Unit/Worker/AutowiringTestCase.php

- Fixed a Workflow hang in cases where a non-promise value was yielded
- Some code was refactored; types were corrected
- How was this tested: added test for the fix

Fix a Workflow hang in cases where a non-promise value is yielded

---

src/DataConverter/DataConverter.php
tests/Fixtures/src/Workflow/TestContextLeakWorkflow.php
tests/Fixtures/src/Workflow/YieldGeneratorWorkflow.php
tests/Functional/ConcurentWorkflowContextTestCase.php
tests/Functional/ConcurrentWorkflowContextTestCase.php
tests/Functional/SimpleWorkflowTestCase.php

Added coroutine tests:
- context doesn't leak when we use timer inside a yielded generator
- a yielded generator is iterated well through coroutine

Add more coroutine tests

---

.github/workflows/static-analysis.yml
composer.json
phpunit.xml.dist
src/Client/Update/UpdateHandle.php
tests/Arch/ArchTest.php

Removed forgotten debug function.
Added Arch test that will prevent this in the future.

Remove forgotten debug function

---

src/Client/ScheduleClient.php
src/Client/ScheduleClientInterface.php
tests/Acceptance/Extra/Schedule/ScheduleClientTest.php
tests/Acceptance/Extra/Schedule/ScheduleUpdateTest.php
tests/Acceptance/Harness/Update/DeduplicationTest.php

Added parameter `query` in `\Temporal\Client\ScheduleClient::listSchedules()`
1. Closes #472 
2. How was this tested: added acceptance test

Expose `query` parameter for Schedule list

---

psalm-baseline.xml
src/Interceptor/Trait/WorkflowOutboundCallsInterceptorTrait.php
src/Interceptor/WorkflowOutboundCalls/UpsertTypedSearchAttributesInput.php
src/Interceptor/WorkflowOutboundCallsInterceptor.php
src/Internal/Workflow/ScopeContext.php
src/Internal/Workflow/WorkflowContext.php
src/Workflow.php
src/Workflow/WorkflowContextInterface.php

- Add Upsert Typed Search Attributes call into the outbound calls interceptor
- Move Upsert SA calls logic into Workflow context

Search Attributes refactoring

---

psalm-baseline.xml
src/Internal/Mapper/WorkflowExecutionInfoMapper.php
src/Workflow/WorkflowExecutionInfo.php
tests/Acceptance/App/Runtime/RRStarter.php
tests/Acceptance/App/Runtime/TemporalStarter.php
tests/Acceptance/Extra/Client/WorkflowClientTest.php
tests/Acceptance/Extra/Schedule/ScheduleClientTest.php
tests/Acceptance/Extra/Schedule/ScheduleUpdateTest.php
tests/Acceptance/Extra/Workflow/RootWorkflowExecutionTest.php
tests/Acceptance/Harness/ChildWorkflow/ResultTest.php
tests/Acceptance/bootstrap.php
tests/Unit/Client/Mapper/WorkflowExecutionInfoMapperTestCase.php
tests/bootstrap.php

Added new fields into Workflow stub -> describe result:
- rootExecution
- firstRunId
- executionDuration
1. Part of #576

Update Workflow description info

---

.github/workflows/run-test-suite.yml
.github/workflows/security-check.yml
.github/workflows/static-analysis.yml
composer.json

Resolved deprecations, simplified steps

Refresh and simplify CI Workflows

---

src/Internal/Declaration/Reader/WorkflowReader.php
tests/Unit/Declaration/Fixture/WorkflowWithConstructor.php
tests/Unit/Declaration/Fixture/WorkflowWithWorkflowInit.php
tests/Unit/Declaration/WorkflowDeclarationTestCase.php

Fix WorkflowInit detection

---

src/Interceptor/WorkflowClientCallsInterceptor.php

Fixed type hint for callback $next
1. Closes 

Fixed type WorkflowClientCallsInterceptor

---

tests/Acceptance/Extra/Versioning/Versioning-default.json
tests/Acceptance/Extra/Versioning/Versioning-v1.json
tests/Acceptance/Extra/Versioning/VersioningTest.php

Added versioning acceptance tests
To check that versioning feature works well on Temporal Dev server
1. Closes #613

Add versioning acceptance tests
