- src/Common/RetryOptions.php
- src/Internal/Assert.php
Fixed the retryable exceptions class list incorrect behavior.
1. Closes issue: https://github.com/temporalio/sdk-php/issues/95
2. How was this tested: 
There is no test case for `withNonRetryableExceptions`, so manual testing only.
No, the example provided in docs is correct.
> Fix retryable exceptions class list in RetryOptions

- docker/buildkite/docker-compose.yml
After https://github.com/temporalio/temporal/pull/1740 `temporalio/auto-setup:latest` points to latest release not latest `master` commit.
> Change docker hub repo to temporaliotest

- src/WorkerFactory.php
- tests/Unit/Declaration/Fixture/CustomReaderWorkerFactory.php
- tests/Unit/Declaration/Fixture/FixedReader.php
- tests/Unit/WorkerFactory/CustomReaderTestCase.php
- tests/Unit/WorkerFactory/WorkerFactoryTestCase.php
Introduced an ability to extend worker factory.
Dunno if I should make other `create*()` methods protected as well, besides reader.
So a custom reader could be used. To be able to read activty/workflow config not only from annotations, but preset arrays etc.
1. Closes https://github.com/temporalio/sdk-php/issues/110
2. How was this tested: Unit tests.
3. Any docs updates needed? No. Its self explanatory and no BC.
> Add support for custom reader in WorkerFactory.

- .github/workflows/testing.yml
- psalm.xml
CI configs seem to be outdated:
- Remove deprecated option from psalm config.
- Add required sockets extension for some tests.
- Fix composer install step for security checks.
> Fix CI issues

- src/Internal/Workflow/WorkflowContext.php
Child workflow should inherit parent namespace if not provided.
Resolves #104
> Fix child workflow namespace propagation

- .gitignore
- composer.json
Unlocked `nesbot/carbon` from `2.52.*` to `^2.52.0`
Temporal was incompatible to latest versions of Laravel when Carbon is locked to `2.52.*`
Tested against latest Laravel version (8.81.0)
> Allow for higher versions of Carbon

- composer.json
I've moved the dependency for `symfony/translation` to the dev-dependencies
The version constraint for `symfony/translation` is very narrow. Currently this severely restricts where the sdk can be installed.
As far as I can tell, this is only to support the test suite, so I've moved it to the dev dependencies. `nesbot/carbon` provides its own, much wider, dependency constraint on `symfony/translation`.
1. Closes 
NA
3. How was this tested:
I've struggled to run some of the test suites locally (specifically `Temporal\Tests\Functional\Client\ActivityCompletionClientTestCase` never seems to pass locally). However, the rest of the tests continue to pass, and I'm using my fork of this in my own project without any issues.
4. Any docs updates needed?
None
> Move symfony/translation to dev-dependencies

- .github/workflows/testing.yml
- src/Internal/Declaration/Prototype/ActivityPrototype.php
- src/Worker/Worker.php
- src/Worker/WorkerInterface.php
- tests/Unit/Activity/ActivityPrototypeTestCase.php
- tests/Unit/Activity/DummyActivity.php
- tests/Unit/Framework/WorkerMock.php
Introduce new method for activity registration. For simple activities without external dependencies:
```php
$worker->registerActivity(MyActivity::class);
```
In case we need dependencies provide a callable factory:
```php
$worker->registerActivity(MyActivity::class, fn(ReflectionClass $class) => $container->create($class->getClass()));
```
> Make activities truly stateless

- src/Promise.php
I've added support for the rest of available [traditional promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#static_methods) methods 
I feel uncomfortable about using `Promise::all([])`, when I need a fulfilled promise 😓 
So I decided to add `Promise::resolve` and the rest of forgotten methods
> Support for full set of promise functions

- src/DataConverter/EncodedValues.php
Small fixes in Encoded values:
1. getValue fails if i.e. `$this->values[0] === null` 
2. fromValues fails when we call i.e. activity with named arguments, `$ev->values` will have named keys
1. Closes #180
> [FIX] Correct encoding of null values, strip names of arguments

- src/Exception/Client/WorkflowException.php
- tests/Unit/Internal/Client/WorkflowStubTest.php
use `static` keyword in WorkflowException::withoutMessage instead of `self` to create new exception
::withoutMessage method is used in classes which extends WorkflowException, `new self` will always create WorkflowException instance.
> Use `static` keyword in WorkflowException::withoutMessage method

- src/Internal/Marshaller/Type/EnumType.php
- tests/Unit/DTO/Enum/EnumDTO.php
- tests/Unit/DTO/Enum/EnumTestCase.php
- tests/Unit/DTO/Enum/ScalarEnum.php
- tests/Unit/DTO/Enum/SimpleEnum.php
Add new marshal type `EnumType` which is available for PHP 8.1
To use all functionality provided by new version of PHP
Unit + Manual
> Enums php81

- src/Internal/Marshaller/Mapper/AttributeMapper.php
- tests/Unit/Internal/Marshaller/Fixture/A.php
- tests/Unit/Internal/Marshaller/Fixture/B.php
- tests/Unit/Internal/Marshaller/MarshallerTestCase.php
Changed behavior for data marshalling.  
Now marshaller throws the `TypeError` when we trying to marshal nullable structure:
```php
final class DeclineReason
{
public function __construct(
public readonly string $code,
public readonly ?string $description = null,
) {}  
}
final class Transaction
{
public function __construct(public readonly ?DeclineReason $reason = null)
{
}
}
```
> Do not pass nullable result to marshaller

- src/Internal/Client/WorkflowStub.php
- tests/Unit/Internal/Client/WorkflowStubTestCase.php
Originally copied from #209 but added a test for it.
> fix: don't fail on null workflow result history

- src/DataConverter/JsonConverter.php
- src/DataConverter/Type.php
- tests/Fixtures/src/Activity/SimpleActivity.php
- tests/Fixtures/src/Workflow/ScalarEnumWorkflow.php
- tests/Fixtures/src/Workflow/SimpleEnumWorkflow.php
- tests/Functional/Client/EnumTestCase.php
Part of code related with serialisation.
To have possibility to put Enum directly as a input to workflow without proxying.
Functional tests
> Enum as a input for workflow

- testing/src/Environment.php
Possibility to set timeout for triggering roadrunner and temporal test server.
In some cases roadrunner needs more time to wake up. We are initiating temporal test server during test bootstrap. Because of time out we do experience random failures in local and CI environments.
> Configurable timeout for test server commands

- .github/workflows/code-style.yml
- .github/workflows/run-test-suite.yml
- .github/workflows/security-check.yml
- .github/workflows/testing.yml
- composer.json
- testing/Readme.md
- testing/src/Environment.php
- tests/bootstrap.php
Added additional check for RR in the Temporal\Testing\Environment::start method
RoadRunner could fail to start for many reasons, for example:
- rr binary doesn't exist (but in that case we could download it I suppose)
- config file not found
- error in the worker setup
It is useful to stop the tests right away and display the error, otherwise the tests are just hang
1. Closes 
- Delete rr binary
- Set wrong path to config in rrCommand (`$environment->start('./rr serve -c missing.rr.yaml');`)
- Put die, or some other error in the worker
> Stop tests and display error if RoadRunner start failed

- src/DataConverter/JsonConverter.php
- src/DataConverter/Type.php
- tests/Unit/DataConverter/DataConverterTestCase.php
Added ability to return associative array from activities with JsonEncoder.
Although @SerafimArts explains in every related issue that json has no support for hashmaps or associative arrays (and this is indisputable true), but we in PHP do have support for it.
And in case of PHP workflow, PHP activity and PHP sdk we control input, output and the type, so I say we should be able to use associative arrays.
Yes, it is json, but we will use stock json_decode to get the required associative array.
Otherwise the SDK should forbid typehint activities with the `array` type. It is counterintuitive: if the `newActivityStub` returns `T` and I have an `array` declared as a return type for a function of `T` I would like to get it, or get an error when I'm trying to create proxy of `T`
1. Closes
#117 …
> Ability to return associative array from an activity

- .github/workflows/run-test-suite.yml
- composer.json
- tests/Unit/DTO/DTOMarshallingTestCase.php
- tests/Unit/DTO/Readonly/ReadonlyPropertiesDTO.php
- tests/Unit/DTO/Readonly/ReadonlyPropertiesTestCase.php
Ok, I remember that readonly didn't work for me, but now they are working, so I created a test case for it. In order for it to work we need to add php 8.1 in CI matrix settings.
But php 8.1 will not work with current lower versions.
The questions is - do you want to add php 8.1 support? If no, I can just add the test and it will be waiting for the version upgrade.
There is another question: how should I go about testing this behavior: with **marshaller** or with **payload converter**? I created both, but I think that one of them is enough. Or both is good?
Added test that covers [readonly properties issue](https://github.com/temporalio/sdk-php/issues/211)
Because issue is open and I though readonly properties would not work, but surprisingly they are working just fine
1. Closes [issue …
> Issue 211. Test for readonly properties

- phpunit.xml
- testing/Readme.md
- testing/src/Environment.php
- testing/src/WithoutTimeSkipping.php
- testing/src/WorkflowTestCase.php
To have possibility to change default port for temporal test server.
Also:
Since output of RR is not visible in PHPunit sometimes it's hard to figure out where is the error. So you can switch test server to real temporal server and see in UI what's happened.
Alternatively Datadog offers https://github.com/temporalio/temporalite own server which also can be use for tests purposes.
> Possibility to configure temporal test server host

- testing/src/Environment.php
Got error on temporal test server starting but not handle it
> Add error output for temporal test server

- src/Worker/ActivityInvocationCache/ActivityInvocationResult.php
- src/Worker/ActivityInvocationCache/InMemoryActivityInvocationCache.php
- src/Worker/ActivityInvocationCache/RoadRunnerActivityInvocationCache.php
- src/Worker/Worker.php
- testing/src/ActivityMocker.php
- testing/src/WorkerFactory.php
This changes improve activity mocking with support for complex return types (and not just native types)
The changed made to allow this are:
- Added an `ActivityInvocationResult` class which encode the response value with the `DataConverter` and wrap it in `EncodedValues` (like a real response) and then save the `EncodedValues` payload to the cache.
- In `ActivityInvocationCacheInterface@execute` method check for the new `ActivityInvocationResult` object and return the encoded values a response
The other changes are only required for passing the `DataConverter` to the cache and to allow an easy override of the cache during test worker construction
Right now activity mocking works only with native types and not with more complex object.
How was this tested:
- All existing tests pass
- The …
> [Testing] Allow mocking activity result with complex objects

- testing/Readme.md
- testing/src/Environment.php
As title of the PR suggest I did separate start of the temporal test server and roadrunner process
To be able to fine tune the test process. For example, I don't want to run temporal in the tests (I have separate container for that), but I do want to start roadrunner worker, there is no straightforward way to do this now.
1. Closes -
I ran external Temporal instance and only used `startRoadRunner` to start worker
updated docs for tests
> Separate start of Temporal Test Server and RoadRunner worker in tests

- composer.json
Extended the `spiral/roadrunner-kv` version.
To use Temporal v2 with Spiral Framework v3
> Extend `spiral/roadrunner-kv` package version

- testing/Readme.md
Instruction how to fix 'temporal-test-server: not found' error on Alpine-based images
in the new Troubleshooting part of the testing README
The error is confusing and might take a lot of time to debug.
> Add Troubleshooting section to testing README with first instruction

- composer.json
I've readded the versions, making it difficult to use `temporal/sdk` in a big project with multiple services and packages.
* Add support for old `psr/log` (all 2.0 and 3.0 changes is it add strict types, I don't see why you would need to enforce it in composer.json).
* Readded support for current LTS symfony versions. 
No big project wants to upgrade to some new version which isn't LTS. In fact upgrading, other than security fixes, if the code is working, is to be skipped.
Please view [this page](https://symfony.com/releases). There isn't even a ^6 LTS version out there.
1. Any docs updates needed?
Nope.
> Revert removing Symfony LTS versions from available versions.

- src/Client/WorkflowClient.php
- src/DataConverter/Type.php
- src/Exception/InstantiationException.php
- src/Internal/Client/WorkflowProxy.php
- src/Internal/Declaration/Instance.php
- src/Internal/Declaration/Instantiator/WorkflowInstantiator.php
- src/Internal/Declaration/Prototype/ActivityPrototype.php
- src/Internal/Declaration/Prototype/Prototype.php
- src/Internal/Declaration/Prototype/PrototypeInterface.php
- src/Internal/Declaration/Reader/WorkflowReader.php
- src/Internal/Workflow/ChildWorkflowProxy.php
- src/Internal/Workflow/ContinueAsNewProxy.php
- tests/Fixtures/src/Workflow/SignalWorkflowWithInheritanceImpl.php
- tests/Fixtures/src/Workflow/SignalledWorkflowReusable.php
- tests/Fixtures/src/Workflow/SignalledWorkflowWithInheritance.php
- tests/Functional/Client/TypedStubTestCase.php
- tests/Functional/Client/UntypedWorkflowStubTestCase.php
- tests/Unit/Declaration/WorkflowDeclarationTestCase.php
- tests/Unit/Declaration/WorkflowNegativeDeclarationTestCase.php
Add an ability to create workflow stub without a handler method, so that signals can be sent to a running workflow via parent reusable interface.
[Workflow interface inheritance](https://docs.temporal.io/php/workflows/#workflow-interface-inheritance) is broken because workflow stub can not be created without a handler method annotated with `WorkflowMethod`.
Handler method is needed only to start a new workflow, but it's okay to send signals or queries to other workflows by stub created from a reusable parent interface.
Integration tests
> Send signal to workflow via parent interface

- src/Internal/Declaration/Instance.php
- src/Internal/Declaration/Reader/ActivityReader.php
- tests/Unit/Activity/ActivityPrototypeTestCase.php
Fix some cases when garbage cycles are got memorized.
The cycles colud be collected with the `gc_collect_cycles` automatically but i think it will be better when we have no these ones.
It might affect some memory metrics for the better.
I use Weak references to check the objects was destroyed after related variables unseting.
> Fix aggregation for garbage cycles in Activity worker

- src/Internal/Transport/Client.php
- src/Internal/Transport/Router/DestroyWorkflow.php
- src/Internal/Workflow/Process/Scope.php
- src/Internal/Workflow/ScopeContext.php
- src/Internal/Workflow/WorkflowContext.php
- tests/Fixtures/Splitter.php
- tests/Fixtures/src/Workflow/AwaitWithSingleTimeoutWorkflow.php
- tests/Fixtures/src/Workflow/AwaitWithTimeoutWorkflow.php
- tests/Fixtures/src/Workflow/TimerWayWorkflow.php
- tests/Fixtures/src/Workflow/TimerWorkflow.php
- tests/Functional/Client/AwaitTestCase.php
- tests/Functional/WorkflowTestCase.php
- tests/Unit/WorkflowContext/AwaitWithTimeoutTestCase.php
- Fixed memory leaks in the case when an uncompleted workflow with an active internal timer (see awaitWithTimeout) is destroyed.
- Call `gc_collect_cycles()` after each Workflow destroy.
- Remove the `WorkflowContext::$timers` collection. Ut is unnecessary since Temporal PHP SDK 2.0 .
- Remove the `WorkflowContext::$asyncAwaits` collection because it is unnecessary.
- Remove unused $loop parameter from the `Temporal\Internal\Transport\Client` constructor.
- Other small improvements.
In the case when the Workflow Worker processes many workflows at the same time
and their number exceeds the value of the `cache_size` parameter, the Workflow Worker will destroy some waiting workflows.
But the Workflow Worker incorrectly destroys workflows with active internal timers: timer promises
will …
> Fix memory leak when a workflow with an active internal timer is destroyed

- src/Internal/Transport/Router/InvokeActivity.php
- tests/Unit/Router/InvokeActivityTestCase.php
If an error happens when executing an activity it will be convenient to know it within a finalizer.
For example, we collect logs and metrics and want to flush or send them only if the activity failed. Currently, within a finalizer there is no way to detect whether it was a success execution or failure.
With unit tests.
Need to make a small update here with `registerActivityFinalizer()` example and provide a snippet with a closure that accepts an exception:
```md
$worker->registerActivityFinalizer(
function (Throwable $error = null) {
if ($error !== null) {
$this->logger->flush();
}
$this->kernel->showtdown();
}
);
```
https://docs.temporal.io/application-development/foundations?lang=php#register-types
> Feature: pass error into activity finalizer

- src/Internal/Marshaller/Mapper/AttributeMapper.php
- src/Internal/Marshaller/Type/ObjectType.php
- src/Internal/Support/Inheritance.php
- tests/Unit/DTO/DeepDTO/ChildDTO.php
- tests/Unit/DTO/DeepDTO/DeepDTOTestCase.php
- tests/Unit/DTO/DeepDTO/ParentDTO.php
1. In case of ObjectType: remember FQCN as `meta->of` if not set.
2. Fixed double unmarshalling in [ObjectType](https://github.com/temporalio/sdk-php/blob/12bfeda200c32fd38e0485a229f4518064d6678e/src/Internal/Marshaller/Type/ObjectType.php#L46)
To add an ability of unmarshalling nested DTOs.
1. Closes #274 
3. How was this tested: 
Added DeepDTOTestCase
4. Any docs updates needed?
No
> feat: unmarshalling of nested DTOs

- src/Workflow/ContinueAsNewOptions.php
Outdated doc block about `workflowExecutionTimeout` was removed
1. Closes #253
> Remove outdated docblock

- testing/src/Environment.php
RoadRunner starting detection improved.
Updated `proto` submodule.
Sometimes RoadRunner starts so fast and PHP fails to catch the moment of launch.
> Maintenance: improve RoadRunner starting detection

- src/Internal/Marshaller/Type/EnumType.php
- src/Internal/Marshaller/TypeFactory.php
- tests/Fixtures/src/Activity/SimpleActivity.php
- tests/Fixtures/src/DTO/WithEnum.php
- tests/Fixtures/src/Workflow/EnumDtoWorkflow.php
- tests/Functional/Client/EnumTestCase.php
- tests/Unit/DTO/Type/EnumType/EnumTestCase.php
Added `EnumType` into type list of TypeFactory for PHP >=8.1.
Aslo `EnumType` was fixed because dataconverters can't encode nested enums.
To support PHP 8.1 enumirations from the box
1. Closes #281, instead of #282
Added feature test with Enum nested into DTO
> Add `EnumType` by default for PHP >=8.1

- testing/Readme.md
- testing/src/Downloader.php
Add javaSdkReleaseUrl parameter to `Temporal\Testing\Downloader`
got error with new version of temporalio/sdk-java v1.18.0-RC1
`/temporal-test-server: /usr/x86_64-linux-gnu/lib/libc.so.6: version 'GLIBC_2.32' not found (required by ./temporal-test-server)`
1. Closes 
> Make java sdk release url configurable in Downloader

- src/Workflow/WorkflowInfo.php
- tests/Unit/DTO/WorkflowInfoTestCase.php
Fixes the problem where WorkflowInfo doesnt retrieve the correct info when using Worker::getInfo().
This also fixes the problem where Workflow::getInfo()->searchableAttributes is null.
I dont know why, but the duplicate Marshal keys of "SearchAttributes" breaks the normal searchAttributes property aswell
Marshal key of Memo property in WorkerInfo
When calling Workflow::getInfo() in a Workflow or an activity, it doesnt return the memo
Manually by creating a new Workflow and using Workflow::getInfo()->memo to retrieve the memo properties.
No, this is a purely a bug
> Fix mapping for the `Memo` field

- composer.json
- src/Activity/ActivityInterface.php
- src/Activity/ActivityMethod.php
- src/Activity/LocalActivityInterface.php
- src/Common/CronSchedule.php
- src/Common/MethodRetry.php
- src/Internal/Marshaller/Meta/Marshal.php
- src/Internal/Marshaller/Meta/MarshalArray.php
- src/Internal/Marshaller/Meta/Scope.php
- src/Workflow/QueryMethod.php
- src/Workflow/ReturnType.php
- src/Workflow/SignalMethod.php
- src/Workflow/WorkflowInterface.php
- src/Workflow/WorkflowMethod.php
Replaced `Spiral\Attributes\NamedArgumentConstructorAttribute` with `Spiral\Attributes\NamedArgumentConstructor` in all attributes.
The **NamedArgumentConstructorAttribute** interface inherits from **Doctrine\Common\Annotations\NamedArgumentConstructorAnnotation** which was removed in version 2.0 of the package: 
https://github.com/doctrine/annotations/pull/470.
> Replacing NamedArgumentConstructorAttribute with NamedArgumentConstructor

- composer.json
Updated versions of RoadRunner PHP packages
To better compatibility with RoadRunner 2023.1
> Update PHP RoadRunner packages versions

- src/Client/GRPC/BaseClient.php
- src/Exception/Client/ServiceClientException.php
UNAVAILABLE and UNKNOWN gRPC errors now are retryable.
> **Note**:
> In the case when a Temporal server is unavailable and by the reason a Client call can't be completed, without a limited retry gRPC call policy it might retry infinitely.
In some cases gRPC connection might be broken or not initialized. In this case we should follow our retry policy.
1. Closes #296 
Manually using [proxy](https://github.com/Shopify/toxiproxy)
> Expand list of retryable gRPC errors

- src/Internal/Transport/Client.php
- src/Internal/Transport/Request/UndefinedResponse.php
Added `UndefinedResponse` command instead of logic exception.
The command is available since RoadRunner 2023.1
The command was added to avoid side effects when workflow worker is restarted.
Before that response to undefined request resulted in a logic exception being thrown.
1. Related with #289 
Tested manually using [that e2e test](https://github.com/roadrunner-server/rr-e2e-tests/tree/undefined-response/php_test_files/temporal/undefined_response)
> Add supporting for RoadRunner `UndefinedResponse` command

- src/Activity/ActivityCancellationType.php
- src/Workflow/ChildWorkflowCancellationType.php
Replace `${var}` with `{$var}`
Since version 8.2 string interpolation ${var} is deprecated - https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation
1. Closes #308
> Fix deprecated interpolation

- src/Client/GRPC/Context.php
- src/Common/SdkVersion.php
- src/Internal/Transport/Router/GetWorkerInfo.php
- tests/Unit/Common/SdkVersionTest.php
PHP SDK now sends its version in each client request correctly - in the request context.
Context fields are:
```
client-name = temporal-php-2
client-version = 2.5.2
```
The client name is changed to `temporal-php-2`, because Temporal Server [doesn't support `temporal-php` client of >= 2.0.0 version](https://github.com/temporalio/temporal/blob/1ca6979915406eaced06c05458380e38e19e2a28/common/headers/version_checker.go#L70C13-L70C13).
For `dev-master` empty string will be sent as a version.
For `2.6.3-beta`, `2.6.3-beta.1`, `2.6.3-beta-1` or `2.6.3-x-dev` the full version will be sent.
The same version rules are applied to the version that sent to RoadRunner.
https://github.com/temporalio/roadrunner-temporal/pull/387/
How was this tested: manually
> Provide PHP-SDK version for RoadRunner and Temporal Server

- src/Internal/Marshaller/Marshaller.php
- src/Internal/Marshaller/Type/ObjectType.php
- tests/Unit/DTO/Type/ObjectType/ObjectTypeTestCase.php
- tests/Unit/DTO/Type/ObjectType/Stub/StdClassObjectProp.php
The Marshaller will now hydrate a stdClass object without any mappers because it's impossible to get setters for stdClass.
ObjectType now detects the `object` type and works with it. Also made a special way to make and hydrate stdClass there.
1. Closes #199
2. How was this tested: manually; added autotests
3. Any docs updates needed? Actually no.
> Fix stdClasses unmarshalling

- src/DataConverter/DataConverter.php
- src/DataConverter/Type.php
- tests/Fixtures/src/Activity/Php82TypesActivity.php
- tests/Fixtures/src/Workflow/Php82TypesWorkflow.php
- tests/Functional/Client/TypedStubTestCase.php
- tests/Unit/DataConverter/DataConverterTestCase.php
Added `null`, `false`, `true` types in the `DataConverter`
Since PHP 8.2 it is possible to use standalone `true`, `false` and `null`:
https://wiki.php.net/rfc/null-false-standalone-types
https://wiki.php.net/rfc/true-type
We need to support.
I think it's not a new feature an we can release it as a fix.
- Closes #328 
- How was this tested:
- added Unit tests and Functional tests
- Functional tests were commented because they break testing with PH <8.2
- Any docs updates needed? no
> [Fix] PHP 8.2 types (null, false, true)

- .github/workflows/run-test-suite.yml
Add Windows tests in CI
Windows tests was removed with #287 because there are [no gRPC binaries in PECL repository](https://pecl.php.net/package/grpc) for PHP 8.2
- https://github.com/php/php-src/issues/10850
- https://github.com/grpc/grpc/issues/32304
- Related thread [Windows PECL build machine died](https://externals.io/message/117494) on PHP Externals
> [CI] Add Windows tests

- src/DataConverter/JsonConverter.php
- src/DataConverter/Type.php
- src/Workflow/WorkflowRunInterface.php
- tests/Fixtures/src/Activity/SimpleActivity.php
- tests/Fixtures/src/Workflow/ArrayOfObjectsWorkflow.php
- tests/Functional/Client/TypeArrayOfObjectsTestCase.php
Allowed possibility to return a list of object from activity/workflow. 
When executing workflow:
```php
/** @var Message[] $result */
$result = $client->start($workflow, 'John')->getResult(Type::arrayOf(Message::class));
```
When executing activity within a workflow:
```php
/** @var Message[] $result */
$result = yield $activity->execute('myActivity', [$input], Type::arrayOf(Message::class));
```
Now, we cant return a list of objects. It will always be an array of arrays.
With a functional test.
Not sure that it is covered in the docs 🤔
> feat: allow to return array of objects

- .github/workflows/run-test-suite.yml
Add CI workflow name
Because CI status badge doesn't work well
> Fix CI badge in readme

- src/Activity/ActivityCancellationType.php
- src/Exception/ExceptionInterceptor.php
- src/Internal/Declaration/WorkflowInstance.php
- src/Internal/Declaration/WorkflowInstance/SignalQueue.php
- src/Internal/Declaration/WorkflowInstanceInterface.php
- src/Internal/Workflow/Process/Process.php
- src/Internal/Workflow/Process/Scope.php
- src/Internal/Workflow/WorkflowContext.php
- tests/Fixtures/src/Workflow/LoopWithSignalCoroutinesWorkflow.php
- tests/Fixtures/src/Workflow/SignalExceptionsWorkflow.php
- tests/Functional/Client/AwaitTestCase.php
- tests/Functional/Client/FailureTestCase.php
- tests/Functional/Client/UntypedWorkflowStubTestCase.php
- tests/docker-compose.yaml
Exceptions from Signal methods now will be propagated and affect Workflow.
Deserialization errors will be ignored. Called Signal method in this case will be skipped.
How was this tested: manually; also added autotests.
> **Note**:
> The fix will be cherry-picked into `master` and `2.7` branches after `2.5.3` release
> Fix exceptions propagation from Signal methods

- src/Internal/Workflow/Process/Scope.php
- tests/Fixtures/src/Workflow/Case335Workflow.php
- tests/Functional/Client/TypedStubTestCase.php
Added additional trigger to flush awaits when coroutine spawns value. Previously only handled when the spawned value was a promise and that promise was handled properly.
Potential issues with awaits being blocked when the signal changes any value and locks with invalid activity call.
1. Closes [no issue]
2. How was this tested: tested via local stand + test suite
none
> Fixes potential issue when signal coroutine won't trigger await due to failed activity call

- phpunit.xml
- tests/Unit/Worker/Transport/RoadRunnerTestCase.php
- tests/Unit/Worker/Transport/RoadRunnerVersionCheckerTestCase.php
Fixed unit tests for the RoadRunner Version Checker. Now the unit tests use mocks and are no longer tied to the RoadRunner version, which was previously specified in the PHPUnit configuration.
> Fixing RoadRunner Version Checker unit tests

- src/Internal/Transport/Client.php
- src/Internal/Transport/ClientInterface.php
- src/Internal/Transport/Router/InvokeQuery.php
- src/Internal/Transport/Router/InvokeSignal.php
- src/Internal/Transport/Router/StartWorkflow.php
- src/Internal/Workflow/Process/Scope.php
- src/Internal/Workflow/WorkflowContext.php
- src/Worker/Transport/Codec/JsonCodec/Decoder.php
- src/Worker/Transport/Codec/ProtoCodec/Decoder.php
- src/Worker/Transport/Command/FailureResponse.php
- src/Worker/Transport/Command/RequestInterface.php
- src/Worker/Transport/Command/Response.php
- src/Worker/Transport/Command/ResponseInterface.php
- src/Worker/Transport/Command/ServerRequest.php
- src/Worker/Transport/Command/ServerRequestInterface.php
- src/Worker/Transport/Command/SuccessResponse.php
- src/WorkerFactory.php
- src/Workflow/WorkflowInfo.php
- testing/src/WorkerFactory.php
- tests/Feature/Testing/CapturedClient.php
- tests/Feature/Testing/TestingClient.php
- tests/Fixtures/src/Workflow/HistoryLengthWorkflow.php
- tests/Functional/HistoryLengthWorkflowTestCase.php
- tests/Unit/DTO/WorkflowInfoTestCase.php
- tests/Unit/Framework/ClientMock.php
- tests/Unit/Framework/Server/ServerMock.php
HistoryLength from #315 (2.7.0) was applied to 2.6.0.
Users should be able to have a more direct way to check if it's time to call continue-as-new than guessing how many events their code produces and counting the loops.
The stable RoadRunner v2023.2 already sends HistoryLength values. After #340 it is easy to provide the feature bit early.
- Closes #222 
- Added autotest.
> Apply changes from 2.7.0 related with HistoryLength to 2.6.0

- .github/workflows/run-test-suite.yml
- composer.json
- src/DataConverter/JsonConverter.php
- src/Internal/Marshaller/Type/UuidType.php
- tests/.rr.silent.yaml
- tests/.rr.yaml
- tests/Fixtures/src/Workflow/SimpleUuidWorkflow.php
- tests/Functional/Client/UuidTestCase.php
- tests/Unit/DTO/DTOMarshallingTestCase.php
- tests/Unit/DTO/Type/UuidType/Stub/UuidObjectProp.php
- tests/Unit/DTO/Type/UuidType/UuidTypeTestCase.php
- tests/Unit/DataConverter/JsonConverterTestCase.php
- tests/Unit/DataConverter/ProtoConverterTestCase.php
- [ramsey/uuid](https://github.com/ramsey/uuid) was moved into the required section from the dev.
- Added tests where Uuid objects passed directly (not nested in DTO)
- Upgraded JsonDataConverter to support Uuid encoding/decoding.
- After DataConverter upgrade, SideEffect returns correct value
1. Closes #345
2. Closes #346
3. How was this tested: added auto-tests
> Better UUID support (passing without nesting)

- .github/workflows/run-test-suite.yml
- psalm-baseline.xml
- src/Internal/Transport/Router/Route.php
- src/Internal/Workflow/WorkflowContext.php
- src/Workflow.php
- src/Workflow/WorkflowContextInterface.php
- tests/Fixtures/src/Workflow/SimpleUuidWorkflow.php
Added new functions:
```php
$uuid  = yield Workflow::uuid();  // Generate a UUID (user doesn't care about the UUID version)
$uuid4 = yield Workflow::uuid4(); // Generate a UUID v4
$uuid7 = yield Workflow::uuid7(); // Generate a UUID v7
```
Just a good sugar.
Java SDK has some similar method `Workflow.randomUUID()` that uses `UUID.randomUUID()` with the SideEffect function.
We do the same.
1. Closes #350
2. How was this tested: added autotests
3. It might be added in the documentation
> Add Workflow::uuid() | uuid4() | uuid7() methods

- composer.json
- psalm-baseline.xml
- src/Internal/Promise/CancellationQueue.php
- src/Internal/Promise/Reasons.php
- src/Internal/Transport/CompletableResult.php
- src/Internal/Transport/CompletableResultInterface.php
- src/Internal/Workflow/Process/Process.php
- src/Internal/Workflow/Process/Scope.php
- src/Internal/Workflow/WorkflowContext.php
- src/Promise.php
- src/Workflow.php
- src/Workflow/CancellationScopeInterface.php
- src/Workflow/ProcessInterface.php
- src/Workflow/WorkflowContextInterface.php
- tests/Fixtures/src/Workflow/CancelSignalledChildWorkflow.php
- tests/Unit/Promise/BaseFunction.php
- tests/Unit/Promise/FunctionAllTestCase.php
- tests/Unit/Promise/FunctionAnyTestCase.php
- tests/Unit/Promise/FunctionMapTestCase.php
- tests/Unit/Promise/FunctionReduceTestCase.php
- tests/Unit/Promise/FunctionSomeTestCase.php
Added supporting for `react/promise` v3 package.
I'm not sure that all 3rd packages was migrated to promises v3, that's why I paid attention to maintaining compatibility with the old promises version.
It adds new features of extended promises like methods `catch()`, `finally()` and `cancel()`.
Also there were added `@template` annotations and better type coverage.
1. Closes #348
2. All old tests passed
The ReactPHP Promise dependency has been updated from version 2 to version 3.
> **Note**: there are no BC breaks in the Temporal SDK, but there are BC breaks in the ReactPHP Promise library.
> If you rely on the functions of the ReactPHP Promise library and use them directly, please familiarize yourself with the list of changes [there](https://github.com/reactphp/promise/releases/tag/v3.0.0) …
> Add supporting for React/Promises v3

- composer.json
- psalm-baseline.xml
- src/Internal/Transport/CompletableResult.php
`react/promise` v3 was removed from `composer.json`
There are unresolved issues regarding this package version.
1. Related issue: https://github.com/temporalio/sdk-php/issues/357
> Remove react/promise v3 from composer.json

- tests/Fixtures/src/Workflow/CancelSignaledChildWorkflow.php
- tests/Fixtures/src/Workflow/SimpleSignaledWorkflow.php
- tests/Functional/Client/TypedStubTestCase.php
- tests/Functional/SimpleWorkflowTestCase.php
A test has been added that demonstrates different SDK work results on different versions of react/promise.
Related issue: https://github.com/temporalio/sdk-php/issues/357
> Add test case where workflow fails with react/promise v3

- src/Client/WorkflowClientInterface.php
Arg $class at the method newRunningWorkflowStub, Contract WorkflowClientInterface
corrects the return type of the newRunningWorkflowStub method
1. Closes 
> [WorkflowClient] fixed return template method newRunningWorkflowStub

- src/Interceptor/Trait/WorkflowInboundCallsInterceptorTrait.php
- src/Interceptor/WorkflowInboundCallsInterceptor.php
- src/Internal/Declaration/Instantiator/WorkflowInstantiator.php
- src/Internal/Declaration/WorkflowInstance.php
- src/Internal/Transport/Router/StartWorkflow.php
- src/Internal/Workflow/Process/Process.php
- src/Internal/Workflow/WorkflowContext.php
- src/Workflow.php
- tests/Fixtures/PipelineProvider.php
- tests/Fixtures/src/Interceptor/HeaderChanger.php
- tests/Fixtures/src/Interceptor/InterceptorCallsCounter.php
`WorkflowInboundInterceptor` has been renamed to `WorkflowInboundCallsInterceptor`
To have the same name of the interceptor like in other SDKs
> Rename `WorkflowInboundInterceptor` to `WorkflowInboundCallsInterceptor`

- composer.json
- src/Client/WorkflowOptions.php
- src/Internal/Client/WorkflowStarter.php
- tests/Unit/DTO/WorkflowOptionsTestCase.php
Added option `workflowStartDelay` and method `withWorkflowStartDelay()` into the `WorkflowOptions`
`StartDelay` will cause Temporal to wait before dispatching the first workflow task.
If the workflow gets a signal before the delay, a workflow task will be dispatched and the rest
of the delay will be ignored.
1. Closes #360
2. How was this tested: unit test that tests immutability of the method. Didn't test with Temporal server
3. Any docs updates needed? ¯\\\_(ツ)\_/¯
> Expose Workflow Start Delay

- src/Client/Schedule/ScheduleHandle.php
- src/Client/Schedule/Spec/ScheduleSpec.php
Hotfix: remove unnecessary parameter from the `ScheduleHandle::delete()`
The parameter is not used in the function body, yet it is declared as required.
Part of #228
> Schedule API fix

- composer.json
- psalm-baseline.xml
- src/Workflow/WorkflowExecution.php
- tests/Unit/DTO/WorkflowExecutionTestCase.php
Fix mapping from proto for `WorkflowExecution`
Updated metafiles
> Prepare to release 2.7.0

- .github/workflows/code-style.yml
- src/Internal/Client/WorkflowStarter.php
- tests/Unit/Internal/Client/WorkflowStarterTestCase.php
Workflow Start Delay is not set in Start Workflow request if it wasn't specified
Temporal doesn't check the interval (Duration) equals to zero.
1. Closes #387 
2. How was this tested: added unit tests
> Don't set Workflow Start Delay if it wasn't specified

- psalm-baseline.xml
- src/Client/Schedule/Spec/ScheduleSpec.php
- src/Internal/Marshaller/TypeFactory.php
- src/Worker/WorkerOptions.php
Fix PSALM issues
During the preparation for the 2.7.4 release, a new version of the static analyzer was released, which added new heuristics. These heuristics found several questionable places in the code.
> Fix static analysis issues

- src/Internal/Client/WorkflowRun.php
- src/Internal/Workflow/ActivityProxy.php
- src/Internal/Workflow/WorkflowContext.php
- tests/Fixtures/src/Activity/JustLocalActivity.php
- tests/Fixtures/src/Workflow/LocalActivityWorkflow.php
- tests/Functional/SimpleWorkflowTestCase.php
- tests/bootstrap.php
Fixed starting for local activities
1. Closes #396 
2. Added auto-tests
> Fix local activities starting

- composer.json
- psalm-baseline.xml
- src/Client/GRPC/BaseClient.php
- src/Common/RetryOptions.php
- src/Exception/Failure/FailureConverter.php
- src/Exception/Failure/TemporalFailure.php
- src/Exception/Failure/TimeoutFailure.php
- src/Exception/TemporalException.php
- src/Internal/Marshaller/Type/DurationJsonType.php
- src/Internal/ServiceContainer.php
- src/Internal/Transport/ClientInterface.php
- src/Worker/Worker.php
- src/Worker/WorkerInterface.php
- src/WorkerFactory.php
- testing/src/WorkerFactory.php
- testing/src/WorkerMock.php
- tests/Fixtures/src/Workflow/AsyncActivityWorkflow.php
- tests/Unit/DTO/RetryOptionsTestCase.php
- tests/Unit/Framework/WorkerMock.php
- Fix marshalling for `RetryOptions` to `json` format to be compatible with the new temporal protobuf messages in RR `>=2023.11`
- Make exception messages shorter and more elegant: hide internal stack trace and deduplicate the error reason
- `composer.json`: add support for RR `2024.1`, add `grpc-ext` in suggestions
- Throw an exception with clear message if Client is used without gRPC extension
- Optimize a few signatures and types to fix static analysis issues
1. Closes #143
2. Closes #394
3. Closes #323
4. Fixes https://github.com/temporalio/roadrunner-temporal/issues/490
5. How was this tested: manually, added autotests
6. Any docs updates needed? No
> Fix intervals marshalling in RetryPolicy and fix small issues

- psalm-baseline.xml
- src/Exception/Failure/FailureConverter.php
- tests/Unit/Exception/FailureConverterTestCase.php
All elements returned by https://www.php.net/manual/en/function.debug-backtrace.php are possible, but not guaranteed. Safeguard added for elements without "class" property.
I encountered this problem when I was using https://laravel.com/docs/10.x/helpers#method-throw-if helper function, that doesn't belong to a class. See screenshot:
> Fix FailureConverter when an exception CallStack contains an incomplete set of keys

- src/Client/WorkflowOptions.php
Removed the experimental flag from StartDelay workflow option
To accurately reflect the current state of the StartDelay workflow option
> Remove experimental flag from StartDelay

- src/Internal/Marshaller/Type/DurationJsonType.php
- tests/Unit/DTO/RetryOptionsTestCase.php
- tests/Unit/DTO/Type/DurationJsonType/DurationJsonTestCase.php
- tests/Unit/DTO/Type/DurationJsonType/Stub/DurationJsonDto.php
Added ability to parse DurationJsonType instance.
It no longer works, and if you need to pass it around to other services or save ActivityOptions somewhere, stuff breaks. I've made this as a check, so it should be BC, and messages using older format shouldn't fail during deployment.
> fix: duration json type parsing fix

- src/Client/Workflow/WorkflowExecutionDescription.php
- src/Client/Workflow/WorkflowExecutionHistory.php
- src/Client/WorkflowClient.php
- src/Client/WorkflowClientInterface.php
- src/Interceptor/Trait/WorkflowClientCallsInterceptorTrait.php
- src/Interceptor/WorkflowClient/DescribeInput.php
- src/Interceptor/WorkflowClientCallsInterceptor.php
- src/Internal/Client/WorkflowRun.php
- src/Internal/Client/WorkflowStub.php
- src/Workflow/WorkflowRunInterface.php
- tests/Functional/Client/UntypedWorkflowStubTestCase.php
Exposed API to describe a Workflow.
Other changes:
- `Temporal\Client\WorkflowExecutionHistory` was moved into another namespace.
- Closes #413 
Use the API to obtain comprehensive information about a started Workflow.
```php
$stub = $workflowClient->newWorkflowStub(SimpleWorkflow::class);
$run = $workflowClient->start($stub, 'Hello World!');
/** @var WorkflowExecutionDescription $description */
$description = $run->describe();
```
You can use the Workflow Describe feature to get the status of a running Workflow.
```php
$stub = $workflowClient->newUntypedRunningWorkflowStub($wfId);
/** @var WorkflowExecutionStatus $status */
$status = $stub->describe()->info->status;
```
> Expose API to describe Workflow

- composer.json
- resources/scripts/generate-client.php
- src/Client/Common/ServerCapabilities.php
- src/Client/GRPC/BaseClient.php
- src/Client/GRPC/ServiceClient.php
- src/Client/GRPC/ServiceClientInterface.php
- src/Common/WorkerVersionStamp.php
- src/Internal/Mapper/WorkflowExecutionInfoMapper.php
- tests/Unit/Client/GRPC/BaseClientTestCase.php
- tests/Unit/Client/Mapper/WorkflowExecutionInfoMapperTestCase.php
Added method `ServiceClient::withAuthKey()`
1. Closes #410 
2. How was this tested: added unit tests
The ClientService now can accept an API key for authentication.
```php
$serviceClient = \Temporal\Client\GRPC\ServiceClient::createSSL(
'temporal.my-project.com:7233',
__DIR__ . '/my-project.key',
__DIR__ . '/my-project.crt',
)->withAuthKey($authKey);
$workflowClient = new \Temporal\Client\WorkflowClient($serviceClient);
```
You may pass your own `Stringable` implementation as a Key to be able to change the key dynamically.
> Expose API key client option

- composer.json
- src/Internal/Support/DateInterval.php
- tests/Unit/Internal/Support/DateIntervalTestCase.php
Fixed DateInterval to protobuf duration casting.
Would cause ```proto_codec_parse_message: json: cannot unmarshal number 5000000000 into Go struct field Duration.Nanos of type int32``` in some cases, specifically:
```
DurationJsonType:93 turns from protobuf format to CarbonInterval
DateInterval:117 division causes f property (float) in CarbonInterval to be set
DateInterval:165 set f propoerty in CarbonInterval causes an interval of 5 seconds to be parsed into protobuf object of [seconds => 5, nanos => 5 000 000 000]
5 000 000 000 doesnt fit into int32 of Duration struct and roadrunner/temporal panics
This would always be an issue with carbon 2 or 3, as the f always can include seconds
```
How was this tested:
Unit tests
> [!NOTE]
> It's the same PR as …
> [BUG] Broken DateInterval to protobuf Duration casting 

- src/Client/WorkflowStubInterface.php
Updated the method comment to make it clear to the user that the method is not 100% asynchronous.
- Part of #426
> Update description for WorkflowStubInterface::startUpdate()

- src/Client/ScheduleClient.php
- src/Client/ScheduleClientInterface.php
`ScheduleClient::listSchedules()`: use namespace value from the Service Client by default
> Use namespace from the Service Client in ScheduleClient::listSchedules()

- src/Internal/Marshaller/Type/ArrayType.php
- tests/Unit/DTO/Type/ArrayType/ArrayDto.php
- tests/Unit/DTO/Type/ArrayType/ArrayTestCase.php
Fixed unmarshalling of typed assoc arrays when a property configured like `MarshalArray(of: SomeClass::class)`
It's more consistently to have assoc array in result in both cases: when typed is specified and when it isn't
1. Closes #433
2. [x] Unit tests
> Fix unmarshalling of typed assoc arrays

- src/Client/Update/UpdateOptions.php
- tests/Unit/DTO/UpdateTestCase.php
Added optional parameter `$lifecycleStage` into `Update\UpdateOptions::new()`
1. Closes #426
2. Docs update: https://github.com/temporalio/documentation/pull/2845
> Add optional parameter `$lifecycleStage` into `Update\UpdateOptions::new()`

- psalm-baseline.xml
- src/DataConverter/EncodedValues.php
- src/DataConverter/ValuesInterface.php
- src/Internal/Workflow/WorkflowContext.php
- tests/Fixtures/WorkerMock.php
- tests/Fixtures/src/Activity/SimpleActivity.php
- tests/Fixtures/src/Workflow/VoidActivityStubWorkflow.php
- tests/Functional/WorkflowTestCase.php
After some recent updates PHP SDK begin to fail on empty array payloads from Golang SDK, while we get EncodedValues their payloads are empty, as such - we don't require DataConverter to decode them.
> Fixes null values receival from Golang Activity SDK

- src/Client/GRPC/Context.php
- tests/Unit/Client/GRPC/BaseClientTestCase.php
Client: fix connection timeout that was converted into static deadline for all requests
Previously, the deadline was calculated at the moment the timeout was set and applied to all subsequent requests. However, the deadline should be recalculated before each request.
- How was this tested: manually
> Client: fix connection timeout

- src/DataConverter/DataConverter.php
- tests/Unit/DataConverter/DataConverterTestCase.php
Added `ProtoBinary` decoder in default set to have an ability to decode protobuf binary messages.
In this case `json/protobuf` converter will still be used for marshalling protobuf messages by default.
1. Closes #455 
> Add ProtoBinary decoder in default set

- psalm-baseline.xml
- src/Workflow/ContinueAsNewOptions.php
- tests/Fixtures/src/Workflow/ContinuaWithTaskQueueWorkflow.php
- tests/Functional/NamedArgumentsTestCase.php
Add inheritance of TaskQueue from the parent when ContinueAsNew options DTO is created
It's expected behavior
1. Closes #453 
> Fix TaskQueue inheritance when workflow is continued as new

- composer.json
- psalm-baseline.xml
- src/Internal/Declaration/WorkflowInstance.php
- src/Internal/Declaration/WorkflowInstanceInterface.php
- src/Internal/Transport/Router/InvokeUpdate.php
- src/Internal/Transport/Server.php
- src/Internal/Workflow/Process/Process.php
- src/Internal/Workflow/Process/Scope.php
- tests/Fixtures/src/Workflow/UpdateExceptionsWorkflow.php
- tests/Functional/Client/FailureTestCase.php
Now exceptionInterceptor is used to detect that exception is error that breaks task or failure that fails update
1. Closes #463
2. How was this tested: added tests but it doesn't run in CI because not supported by test server
> Divide errors and failures in updates

- src/Client/Update/UpdateHandle.php
- src/Client/WorkflowStubInterface.php
- src/Exception/Client/WorkflowFailedException.php
- src/Internal/Client/WorkflowStub.php
- tests/Acceptance/Extra/Update/UntypedStubTest.php
- tests/Acceptance/Harness/Update/AsyncAcceptTest.php
Added method `\Temporal\Client\WorkflowStubInterface::getUpdateHandle()`
```php
$stub = $workflowClient->newUntypedRunningWorkflowStub($wfId, $wfRunId, $wfType);
$handle = $stub->getUpdateHandle($updateId);
$handle->getResult(5);
```
1. Closes #458
> Expose `WorkflowStub::getUpdateHandle`

- composer.json
- psalm-baseline.xml
- src/FeatureFlags.php
- src/Internal/Transport/Router/RouteInterface.php
- src/Internal/Transport/Router/StartWorkflow.php
- src/Internal/Workflow/Process/DeferredGenerator.php
- src/Internal/Workflow/Process/Process.php
- src/Internal/Workflow/Process/Scope.php
- src/Internal/Workflow/ScopeContext.php
- src/Worker/LoopInterface.php
- src/Workflow/ScopedContextInterface.php
- tests/Acceptance/App/Feature/WorkflowStubInjector.php
- tests/Acceptance/App/RuntimeBuilder.php
- tests/Acceptance/Harness/Signal/SignalWithStartTest.php
A fix has been added where the Workflow Method starts after the initial signals on signalWithStart().
To avoid a breaking change, the class `\Temporal\FeatureFlags` with the flag `$workflowDeferredInitialization = false` was added. To activate the new behavior, set this flag to `true`.
```php
// Set flags
\Temporal\FeatureFlags::$workflowDeferredHandlerStart = true;
// Create Workers
$factory = WorkerFactory::create();
// ...
```
> [!NOTE]
> The feature marked as experimental
1. Closes #457 
> Start Workflow Method after Signal if it's' signalWithStart

- src/Internal/ServiceContainer.php
- src/Internal/Workflow/Process/DeferredGenerator.php
- src/Internal/Workflow/Process/HandlerState.php
- src/Internal/Workflow/Process/Scope.php
- src/Internal/Workflow/ScopeContext.php
- src/Internal/Workflow/WorkflowContext.php
- src/Workflow.php
- src/Workflow/HandlerUnfinishedPolicy.php
- src/Workflow/WorkflowContextInterface.php
- tests/Acceptance/Extra/Update/UntypedStubTest.php
- tests/Acceptance/Extra/Workflow/AllHandlersFinishedTest.php
Added the new method  `Workflow::allHandlersFinished()`
```php
yield Workflow::await(
static fn() => Workflow::allHandlersFinished(),
);
```
Added HandlerUnfinishedPolicy enum
1. Closes #447 
> Expose `Workflow::allHandlersFinished()`

- src/Workflow/WorkflowInterface.php
I made the WorkflowInterface attribute not final
I am extending this attribute to allow myself to add more properties. The additional properties will help me with building the container and workers. 
Example:
```php
use Temporal\Workflow\WorkflowInterface;
class MyWorkflowInterface extends WorkflowInterface
{
public function __construct(
public string $workerName, 
){}
}
```
Now I can create a bunch of worker configuration and map it with my workflows and let my applications service container build the workers for me. 
This is similar to `ActivityInterface` attribute. 
I did not test at all. 
2. Any docs updates needed?
Nope
> Remove final from WorkflowInterface

- src/Client/GRPC/BaseClient.php
- src/Client/Update/UpdateHandle.php
- src/Client/WorkflowStubInterface.php
- src/Exception/Client/CanceledException.php
- src/Exception/Client/TimeoutException.php
- src/Exception/Client/WorkflowUpdateException.php
- src/Exception/Client/WorkflowUpdateRPCTimeoutOrCanceledException.php
- src/Internal/Client/WorkflowStub.php
- tests/Acceptance/App/Attribute/Client.php
- tests/Acceptance/Extra/Update/TimeoutTest.php
Added `WorkflowUpdateRPCTimeoutOrCanceledException` that will be thrown instead of `TimeoutException` in Update cases.
I haven't added the new `RPCTimeoutOrCanceledException` because we already have a similar RPC specific timeout exception (`\Temporal\Exception\Client\TimeoutException`)
Added `\Temporal\Exception\Client\CanceledException` for client canceled calls
1. Closes #436
2. How was this tested: added auto-tests
> Add WorkflowUpdateRPCTimeoutOrCanceledException

- src/Promise.php
One less use statement
It was not used nor is it valid (ie class does not exist)
> Remove unused and invalid use statement

- src/Internal/Declaration/Prototype/ActivityPrototype.php
- tests/Unit/Activity/ActivityPrototypeTestCase.php
Adding a getter for ActivityPrototype::$factory
Whenever I start my workers, I replace all `ActivityPrototype` with a decorated version of my activities. I do this to add support for EventDispatcher. Ie I dispatch event before and after an activity is executed. 
So I need to rebuild the `ActivityPrototype`. 
Unit tests
Nope
> Add getter for ActivityPrototype::$factory

- psalm-baseline.xml
- src/Internal/Declaration/WorkflowInstance.php
- src/Internal/Declaration/WorkflowInstanceInterface.php
- src/Internal/Workflow/WorkflowContext.php
- src/Workflow.php
- src/Workflow/WorkflowContextInterface.php
- tests/Acceptance/Extra/Update/DynamicUpdateTest.php
Added `Workflow::registerUpdate($name, $handler, $validator)` to register updates dynamically
```php
#[WorkflowMethod]
public function handler()
{
Workflow::registerUpdate(
'my-update',
fn(Task $task) => $this->queue->push($task),
fn(Task $task) => $this->isValidTask($task) or throw new \InvalidArgumentException('Invalid task'),
);
}
```
1. Closes #497 
2. How was this tested: added autotests
> Register Update handler dynamically

- psalm-baseline.xml
- src/Client/Schedule/Action/StartWorkflowAction.php
- src/Client/Schedule/Info/ScheduleDescription.php
- src/Client/Schedule/ScheduleHandle.php
- src/Client/Schedule/Update/ScheduleUpdate.php
- src/Client/Schedule/Update/ScheduleUpdateInput.php
- src/Internal/Traits/CloneWith.php
- testing/src/Environment.php
- tests/Acceptance/App/TestCase.php
- tests/Acceptance/Extra/Schedule/ScheduleUpdateTest.php
- tests/Unit/Schedule/ScheduleHandleTestCase.php
- Added the ability to update Schedule via a closure, similar to other SDKs.
- Added the ability to modify SearchAttributes through Schedule::update.
1. Closes #478 
2. How was this tested: added autotests
> Schedule update with Search Attributes

- src/Client/WorkflowStubInterface.php
Fix a small typo in the docstring
> Fix typo in `hasExecution` docstring

- src/Worker/ActivityInvocationCache/RoadRunnerActivityInvocationCache.php
For the ActivityMocker invocation cache a hard-coded address was used for the roadrunner RPC settings, in certain scenarios it is desirable to change it. This is inline with other parts of the code that set the RPC address.
On my local PC i am running temporal/roadrunner combination for local development purposes
For PHPUnit tests i am spinning up the temporal-test-server (for the time shifting ability) and another roadrunner which connects to this temporal server. The RPC settings on the second roadrunner need to be different to not clash with the first process.
1. Closes 
Tested by making changes locally
None
> Use environment options to create RRActivityInvocationCache

- src/Client/GRPC/BaseClient.php
In the code that calculates the interval between attempts, milliseconds were passed to the wait function, whereas microseconds should have been passed.
> Fix intervals between retries in Client API calls

- .github/workflows/run-test-suite.yml
- phpunit.xml.dist
- psalm-baseline.xml
- src/Client/Schedule/Spec/ScheduleSpec.php
- src/Exception/Client/ServiceClientException.php
- src/Internal/Mapper/ScheduleMapper.php
- tests/Unit/Router/InvokeActivityTestCase.php
- tests/Unit/Router/StartWorkflowTestCase.php
- Fix deprecation on Service Client exception parsing
- Resolve all the deprecations in tests
- Deprecate `ScheduleSpec::$excludeCalendarList` and related methods; stop mapping it into the related protobuf message
It may throw an error depending on user environment
1. Closes #522
2. Closes #501 (tests on windows are run only with protobuf ext)
> Resolve deprecations

- src/Interceptor/WorkflowInbound/QueryInput.php
- src/Interceptor/WorkflowInbound/SignalInput.php
- src/Interceptor/WorkflowInbound/UpdateInput.php
- src/Interceptor/WorkflowInbound/WorkflowInput.php
- src/Internal/Transport/Router/InvokeQuery.php
- src/Internal/Transport/Router/InvokeUpdate.php
- src/Internal/Transport/Router/StartWorkflow.php
- src/Internal/Workflow/Process/Process.php
WorkflowInboundInterceptor:
- added isReplaying flag
- added workflow info into query input
> Extend interceptors context DTOs

- composer.json
- psalm-baseline.xml
- src/Client/GRPC/BaseClient.php
- src/Internal/Transport/Router/GetWorkerInfo.php
- src/Worker/ServiceCredentials.php
- src/WorkerFactory.php
- testing/src/WorkerFactory.php
- tests/Unit/Framework/WorkerFactoryMock.php
- tests/Unit/Worker/ServiceCredentialsTestCase.php
- Added `ServiceCredentials` DTO to have the ability to provide connection configuration from the PHP side to RoadRunner.
Related https://github.com/temporalio/roadrunner-temporal/pull/575
- How was this tested: can't test automatically
- Any docs updates needed?
> Send ApiKey to RoadRunner with WorkerInfo

- testing/src/Environment.php
Possibility to add parameters for test server
To have better configuration options
1. Closes 
> Parameters for test server

- psalm-baseline.xml
- src/WorkerFactory.php
- testing/src/WorkerFactory.php
Made parameter `$credentials` in `\Temporal\WorkerFactory::__construct()` optional
To fix BC
> Fix BC in WorkerFactory constructor

- tests/Acceptance/Harness/Update/WorkerRestartTest.php
The `WorkerRestartTest` has a floating error (race condition between phpunit runtime and runtime into Roadrunner workers activity). The `WorkerRestartTest` is unstable.
The key-value cache (`StorageInterface`) has an **in-memory** implementation. Therefore set values are reset upon roadrunner restart.
1. First the activity is locked, key `KV_ACTIVITY_BLOCKED` is set to `true`
2. Then Roadrunner is restarted
2.1. `$runner->stop();`, `KV_ACTIVITY_BLOCKED` key is reset, because storage is **in-memory**
2.2. `$runner->start();`
2.3. Roadrunner starts the workers which may execute activity code **immediately**
3. Then the activity is unlocked (key `KV_ACTIVITY_BLOCKED` is set to `false`)
The activity code throws an exception, if key `KV_ACTIVITY_BLOCKED` has a value **that is not boolean** …
> Fix a floating error in the WorkerRestart test

- psalm-baseline.xml
- src/Internal/Client/ResponseToResultMapper.php
- tests/Acceptance/Extra/Update/UntypedStubTest.php
Fix issue when a workflow stub without defined type runs an update method
1. Closes #544
2. How was this tested: added acceptance test
> Fix calling update method with unknown workflow type

- psalm-baseline.xml
- src/Client/Schedule/ScheduleOptions.php
- src/Client/ScheduleClient.php
- tests/Unit/Schedule/ScheduleClientTestCase.php
- tests/Unit/Schedule/ScheduleOptionsTestCase.php
- `ScheduleOptions->naemspace` has `null` value by default instead of `"default"`
- Deprecate `namespace` property and `withNamespace()` method in `ScheduleOptions`
- Use `namespace` from the ClientOptions as a fallback value when a Schedule is created
1. Closes #548
2. How was this tested: added unit tests
> Use `namespace` from ClientOptions on creating of Schedule

- phpunit.xml.dist
- src/Internal/Declaration/Dispatcher/Dispatcher.php
- src/Internal/Workflow/Process/DeferredGenerator.php
- src/Internal/Workflow/Process/Scope.php
- src/Workflow.php
- tests/Acceptance/Extra/Schedule/ScheduleClientTest.php
- tests/Acceptance/Extra/Update/UntypedStubTest.php
- tests/Acceptance/Extra/Update/UpdateWithStartTest.php
- tests/Acceptance/Extra/Workflow/AllHandlersFinishedTest.php
- tests/Acceptance/Extra/Workflow/MutexRunLockedTest.php
- tests/Acceptance/Harness/ChildWorkflow/ThrowOnExecuteTest.php
- tests/Unit/Worker/AutowiringTestCase.php
- tests/Unit/Workflow/DeferredGeneratorTestCase.php
- All Acceptance tests now run, not just half.
- Fixed all identified errors.
- Sync tests behavior with Temporal CLI 1.2.0
1. Closes #550
> Activate Acceptance/Extra tests, fix bugs

- src/Internal/Marshaller/Type/DurationJsonType.php
- src/Internal/Transport/Request/UpsertSearchAttributes.php
- src/Internal/Transport/Request/UpsertTypedSearchAttributes.php
- tests/Unit/DTO/Type/DurationJsonType/DurationJsonTestCase.php
- tests/Unit/DTO/Type/DurationJsonType/Stub/DurationJsonDto.php
Marshaller decodes null value into an empty interval when a message of Duration type expected
1. Closes #286
2. How was this tested: tests added
> Fix unmarshalling of ScheduleSpec with null jitter

- src/Internal/Declaration/WorkflowInstance.php
- src/Internal/Declaration/WorkflowInstanceInterface.php
- src/Workflow/WorkflowInit.php
- tests/Acceptance/Extra/Workflow/InitMethodTest.php
Attribute`InitMethod` renamed to `WorkflowInit`
Other SDKs have init-attributes with the same name
> Rename `InitMethod` to `WorkflowInit`

- src/Interceptor/Trait/WorkflowOutboundCallsInterceptorTrait.php
- src/Workflow.php
- tests/Acceptance/App/Runtime/RRStarter.php
- tests/Acceptance/Extra/Workflow/MemoTest.php
- tests/Unit/Interceptor/TraitsTestCase.php
Added `upsertMemo()` method with default implementation for WorkflowOutboundCallsInterceptor.
> Add default implementation for upsertMemo method in interceptors

- psalm-baseline.xml
- psalm.xml
- src/Internal/Marshaller/Type/DurationJsonType.php
- src/Internal/Support/DateInterval.php
- tests/Acceptance/Extra/TaskQueue/WorkflowATest.php
- tests/Acceptance/Extra/TaskQueue/WorkflowBTest.php
- tests/Acceptance/Harness/ContinueAsNew/ContinueAsSameTest.php
- tests/Unit/Internal/Support/DateIntervalTestCase.php
After a detailed review of the codebase and running various tests, it turned out that Issue #481 was not confirmed. Workflow Types do not leak beyond their TaskQueue. The reason for the failing tests was in the test settings in Harness.
Another conversion of `null` values to an empty interval (valid only for Cloud environments) was found and fixed.
1. Closes #555 
2. Closes #481 
3. How was this tested: 
- added autotests
- tested on Cloud in Harness
> Fix decoding of non-nullable interval fields when null is gotten

- src/Internal/Declaration/Reader/ActivityReader.php
- src/Internal/Declaration/Reader/Reader.php
- tests/Unit/Activity/ActivityPrototypeTestCase.php
- tests/Unit/Activity/DummyActivity.php
- tests/Unit/Activity/MagicActivity.php
- tests/Unit/Router/InvokeActivityTestCase.php
Magic methods that was not marked by the ActivityMethod attribute will not be registered as activity methods
1. Closes #566
> Skip magic methods in Activity classes

- src/Client/GRPC/BaseClient.php
- src/Client/ScheduleClient.php
- src/Client/WorkflowClient.php
- tests/Unit/Client/GRPC/BaseClientTestCase.php
- tests/Unit/Schedule/ScheduleClientTestCase.php
- Fix: Auth Key doesn't affect other metadata now
- Added `Temporal-Namespace` header into each client request
To be able to work with Temporal Cloud
1. Closes #582
> Expose Namespace in client requests metadata

- .gitignore
- psalm-baseline.xml
- src/Internal/Transport/Client.php
- src/Internal/Workflow/ScopeContext.php
- src/Internal/Workflow/WorkflowContext.php
- src/Workflow/WorkflowContextInterface.php
- tests/Acceptance/App/Attribute/Client.php
- tests/Unit/Framework/ClientMock.php
Fixed a memory leak where `upsertSearchAttributes`, `upsertTypedSearchAttributes`, and `upsertMemo` requests were being stored indefinitely in memory waiting for responses that RoadRunner never sends.
Workflow workers were accumulating these pending requests, causing memory growth up to 2GB. This led to performance degradation due to excessive garbage collection cycles (`gc_collect_cycles()`), ultimately resulting in timeouts.
> Fix memory leak on upsert SA/MEMO requests

- src/Interceptor/WorkflowInboundCallsInterceptor.php
- src/Interceptor/WorkflowOutboundCallsInterceptor.php
- src/Interceptor/WorkflowOutboundRequestInterceptor.php
- src/Internal/ServiceContainer.php
- src/Internal/Workflow/Logger.php
- src/Internal/Workflow/Process/Process.php
- src/Internal/Workflow/WorkflowContext.php
- src/Worker/FeatureFlags.php
- src/Worker/Logger/StderrLogger.php
- src/Worker/WorkerFactoryInterface.php
- src/Worker/WorkerOptions.php
- src/WorkerFactory.php
- src/Workflow.php
- src/Workflow/WorkflowContextInterface.php
- testing/src/WorkerFactory.php
- tests/Acceptance/App/Logger/ClientLogger.php
- tests/Acceptance/App/Logger/FileLogger.php
- tests/Acceptance/App/Logger/LogRecord.php
- tests/Acceptance/App/Logger/LoggerFactory.php
- tests/Acceptance/App/Runtime/Feature.php
- tests/Acceptance/App/TestCase.php
- tests/Acceptance/Extra/Workflow/AllHandlersFinishedTest.php
- tests/Acceptance/Extra/Workflow/LoggerTest.php
- tests/Acceptance/worker.php
- tests/Unit/Framework/WorkerFactoryMock.php
- tests/Unit/Internal/Workflow/LoggerTestCase.php
- tests/Unit/Router/InvokeActivityTestCase.php
- tests/Unit/Router/StartWorkflowTestCase.php
Exposed Logger in Workflow with StderrLogger by default
1. Closes #533 
Logging is a critical component for monitoring and troubleshooting your Temporal applications. The PHP SDK provides a dedicated logger for use within Workflows that respects replay semantics and adds contextual information automatically.
To get a PSR-3 compatible logger in your Workflow code, use the `Workflow::getLogger()` method:
```php
use Temporal\Workflow;
#[Workflow\WorkflowInterface]
class MyWorkflow
{
#[Workflow\WorkflowMethod]
public function execute(string $param): \Generator
{
Workflow::getLogger()->info('Workflow started', ['parameter' => $param]);
// Your workflow implementation
Workflow::getLogger()->info('Workflow completed');
return …
```
> Add Workflow Logger

- .github/workflows/run-test-suite.yml
- .github/workflows/security-check.yml
- .github/workflows/static-analysis.yml
- composer.json
- dload.xml
- psalm-baseline.xml
- src/Client/Workflow/WorkflowExecutionDescription.php
- src/Internal/Transport/Client.php
- src/Internal/Transport/ClientInterface.php
- src/Internal/Transport/DetachedClient.php
- src/Internal/Transport/Router/StartWorkflow.php
- src/Internal/Workflow/WorkflowContext.php
- src/Workflow/WorkflowExecutionConfig.php
- tests/Feature/Testing/CapturedClient.php
- tests/Fixtures/src/Workflow/DetachedScopeWorkflow.php
- tests/Functional/WorkflowTestCase.php
- tests/Unit/Framework/ClientMock.php
- tests/Unit/Framework/Expectation/WorkflowResult.php
- tests/Unit/Framework/Server/ServerMock.php
- tests/Unit/Framework/WorkerMock.php
- tests/Unit/Router/StartWorkflowTestCase.php
- tests/Unit/WorkflowContext/GetVersionTestCase.php
- Remove internal annotation from WorkflowExecutionDescription
- Now the internal Client is forked for each Workflow. Each Client fork will remove its requests from the parent one when the related Workflow context is destroying.
1. Closes #597 
> Fix collecting Workflow requests after destroying

- psalm-baseline.xml
- src/Client/Update/UpdateHandle.php
- src/Exception/Failure/FailureConverter.php
Replaced the approach in PR #526 by modifying `UpdateHandle::fetchResult()` to repeatedly poll the Temporal service until either the configured deadline is reached or a response is received. This eliminates the need for a special `WorkflowUpdateResultException` when a Workflow Update Request is stuck in ADMITTED status.
This implementation aligns with other Temporal SDKs by continuing to poll rather than throwing an exception when updates are stuck. This provides a more consistent behavior across Temporal implementations and better handles scenarios where workflows are delayed due to unavailable workers or failed workflow tasks.
1. Tested manually
> Continuous polling in UpdateHandle::fetchResult() until deadline

- src/Activity.php
- src/Activity/ActivityContextInterface.php
- src/Internal/Activity/ActivityContext.php
- src/Internal/Declaration/Prototype/WorkflowPrototype.php
- src/Internal/Declaration/Reader/WorkflowReader.php
- src/Internal/Declaration/WorkflowInstance.php
- src/Internal/Transport/Router/InvokeActivity.php
- src/Internal/Transport/Router/StartWorkflow.php
- src/Internal/Workflow/Process/Process.php
- src/Internal/Workflow/Process/Scope.php
- src/Internal/Workflow/WorkflowContext.php
- src/Workflow.php
- tests/Acceptance/App/Attribute/Worker.php
- tests/Acceptance/App/Feature/WorkerFactory.php
- tests/Acceptance/App/Logger/ClientLogger.php
- tests/Acceptance/App/TestCase.php
- tests/Acceptance/Extra/Interceptors/ContextTest.php
- tests/Acceptance/Extra/Workflow/FallbackHandlersTest.php
- tests/Acceptance/worker.php
- tests/Fixtures/src/Interceptor/HeaderChanger.php
- Added `Activity::getInstance()` and `Workflow::getInstance()`
- Changed workflow execution flow:
- First, the Workflow is initialized.
- It is recommended not to make calls to start Activity, ChildWorkflow, Timer, etc.
- If the `#[WorkflowInit]` attribute is present, the arguments are resolved.
- `WorkflowInboundCallInterceptor::execute()` is called
- Arguments from the previous step are used, but they can be overridden.
- Workflow Handler is called.
- Now errors from `WorkflowInboundCallInterceptor::execute()` are recorded in the Workflow history.
Tests:
- Acceptance Tests: added ability to customize workers per TaskQueue in tests.
- Added tests for workflow dynamic handlers.
1. Closes #546
> Expose Activity and Workflow instance from context

- src/Client/WorkflowClient.php
- src/Interceptor/Trait/WorkflowClientCallsInterceptorTrait.php
- src/Interceptor/WorkflowClient/UpdateWithStartOutput.php
- src/Interceptor/WorkflowClientCallsInterceptor.php
- src/Internal/Client/WorkflowStarter.php
- tests/Fixtures/src/Interceptor/InterceptorCallsCounter.php
- tests/Fixtures/src/Workflow/Interceptor/UpdateHeadersWorkflow.php
- tests/Functional/.rr.silent.yaml
- tests/Functional/Interceptor/InterceptorsTestCase.php
- Fixed `WorkflowClientCallsInterceptor::updateWithStart()` signature to match value returned from `WorkflowStarter::updateWithStart()`
- Added test case to cover fixed area.
Because whenever `WorkflowClientCallsInterceptor` implementation is provided and `updateWithStart()` is called exception happens.
Example output, from the provided test case, if signature change is reverted
```
TypeError: Temporal\Tests\Interceptor\InterceptorCallsCounter::updateWithStart(): Return value must be of type Temporal\Client\Update\UpdateHandle, array returned
```
1. Closes _nothing_ (did not find any related issue)
See the added test case
No
> fix: incorrect updateWithStart signature

- src/Internal/Marshaller/Mapper/AttributeMapper.php
This PR related to the discord discussion about a bug where error handler can be reassigned so this error is not being caught.
null-coalesce will serve the same purpose here and will not rely on try/catch
> Null coalesce in AttributeMapper instead of try/catch

- psalm-baseline.xml
- src/Client/WorkflowClientInterface.php
This pull request makes a minor change to the `src/Client/WorkflowClientInterface.php` file by removing the `@note Experimental feature.` annotation from the `updateWithStart` method's PHPDoc block.
> Remove experimental note from updateWithStart client method
